name: Toot

on:
  workflow_dispatch:
  schedule:
  - cron: '0 14 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Configure Python with pip cache
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: |
        poetry install
    - name: Build package
      run: |
        poetry build --format wheel
    - name: Install package
      run: |
        poetry run pip install dist/*.whl
    - name: Toot random line from database
      run: |-
        post-bartleby-line
